<?php
/** @var $block Current
 *  @var $escaper Escaper
 * */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Html\Link\Current;
$attributesHtml = '';
$attributes = $block->getAttributes();
if ($attributes) {
    foreach ($attributes as $attribute => $value) {
        $attributesHtml .= ' ' . $attribute . '="' . $block->escapeHtml($value) . '"';
    }
}
?>
<li class="nav item <?= $block instanceof Current && $block->isCurrent() ? 'current' : '' ?>">
    <a href="<?= $escaper->escapeHtml($block->getHref()) ?>"
    <?= $block->getTitle()
    ? ' title="' . $escaper->escapeHtml(__($block->getTitle())) . '"'
    : '' ?>
    <?= $attributesHtml ?>>

        <?php if ($block->getIsHighlighted()): ?>
            <strong>
        <?php endif; ?>

        <?= $escaper->escapeHtml(__($block->getLabel())) ?>

        <?php if ($block->getIsHighlighted()): ?>
            </strong>
        <?php endif; ?>
    </a>
</li>
